// Generated from chat/**/theme.mp3. Run npm run generate:dialogue-themes after adding themes.
export const DIALOGUE_THEME_SOURCES = {
  "alex s": "chat/alex s/theme.mp3",
  "andy": "chat/andy/theme.mp3",
  "bochra": "chat/bochra/theme.mp3",
  "chris": "chat/chris/theme.mp3",
  "dan": "chat/dan/theme.mp3",
  "alice": "chat/alice/player/theme.mp3",
  "ed": "chat/ed/player/theme.mp3",
  "georgia": "chat/georgia/theme.mp3",
  "ju": "chat/ju/theme.mp3",
  "joe": "chat/joe/theme.mp3",
  "katie": "chat/katie/theme.mp3",
  "lucy": "chat/lucy/theme.mp3",
  "maddy": "chat/maddy/theme.mp3",
  "oscar": "chat/oscar/theme.mp3",
  "sam": "chat/sam/player/theme.mp3",
  "alex w": "chat/alex w/player/theme.mp3",
  "aliya": "chat/aliya/example/theme.mp3",
  "helen": "chat/helen/player/theme.mp3",
  "julian": "chat/julian/player/theme.mp3",
  "josh": "chat/josh/example/theme.mp3",
  "marina d": "chat/marina d/player/theme.mp3",
  "meli": "chat/meli/player/theme.mp3",
  "mason": "chat/mason/player/theme.mp3",
  "niall": "chat/niall/player/theme.mp3",
  "mike": "chat/mike/player/theme.mp3",
  "noel": "chat/noel/player/theme.mp3",
  "real": "chat/real/andy/player/theme.mp3",
  "rei": "chat/rei/player/theme.mp3"
} as const;
