// Generated by scripts/generate-profiles.mjs.
import { PROFILE_IMAGE_SOURCES } from './profile-images.generated.js';

export function profileImageSource(name: string): string | null {
  const normalizedName = name.trim().toLowerCase();
  const exactMatch = PROFILE_IMAGE_SOURCES[normalizedName as keyof typeof PROFILE_IMAGE_SOURCES];
  if (exactMatch) return exactMatch;
  const matchingKey = Object.keys(PROFILE_IMAGE_SOURCES).find((key) =>
    normalizedName.startsWith(`${key} `) || key.startsWith(`${normalizedName} `),
  );
  return matchingKey ? PROFILE_IMAGE_SOURCES[matchingKey as keyof typeof PROFILE_IMAGE_SOURCES] : null;
}

export function setProfileImage(image: HTMLImageElement, name: string, prefix = ''): void {
  const source = profileImageSource(name);
  image.hidden = !source;
  image.alt = source ? `${name} profile` : '';
  if (source) image.src = `${prefix}${source}`;
  else image.removeAttribute('src');
}
