// Generated from chat/**/profile.(png|jpg|jpeg). Run npm run generate:profiles after adding profiles.
export const PROFILE_IMAGE_SOURCES = {
  "alex s": "chat/alex s/profile.jpg",
  "chris": "chat/chris/player/profile.png",
  "georgia": "chat/georgia/player/profile.png",
  "ju": "chat/ju/player/profile.png",
  "lucy": "chat/lucy/player/profile.png",
  "tim": "chat/tim/player/profile.png",
  "adam": "chat/adam/player/profile.png",
  "alex w": "chat/alex w/player/profile.png",
  "alice": "chat/alice/player/profile.png",
  "aliya": "chat/aliya/example/profile.png",
  "andy": "chat/andy/player/profile.png",
  "bochra": "chat/bochra/player/profile.png",
  "dan": "chat/dan/player/profile.png",
  "ed": "chat/ed/player/profile.png",
  "joe": "chat/joe/player/profile.png",
  "helen": "chat/helen/player/profile.png",
  "josh": "chat/josh/example/profile.png",
  "julian": "chat/julian/player/profile.png",
  "katy": "chat/katy/player/profile.png",
  "katie": "chat/katie/player/profile.png",
  "maddy": "chat/maddy/example/profile.png",
  "mason": "chat/mason/player/profile.png",
  "marina d": "chat/marina d/player/profile.png",
  "meli": "chat/meli/player/profile.png",
  "mike": "chat/mike/player/profile.png",
  "niall": "chat/niall/player/profile.png",
  "oscar": "chat/oscar/player/profile.png",
  "noel": "chat/noel/player/profile.png",
  "rei": "chat/rei/player/profile.png",
  "sam": "chat/sam/player/profile.png"
} as const;
