// Generated from prepared assets. Stale copies fall back to the original source.
export const WEB_IMAGE_SOURCES: Readonly<Record<string, string>> = {
  "img/external/overworld.png": "img/web/overworld.2a91b8c6d3f7.webp",
  "img/external/road.png": "img/web/road.c2c9b53037c8.webp",
  "img/external/tree.png": "img/web/tree.23ab3b6252ee.webp",
  "img/external/door-open.png": "img/web/door-open.9ae55aea83dd.webp",
  "img/external/billboard-unfinished.png": "img/web/billboard-unfinished.006ff4176196.webp",
  "img/external/billboard-finished.png": "img/web/billboard-finished.bb974f79c9ce.webp",
  "img/external/buildings/snow-mansion.png": "img/web/snow-mansion.6d639370a96d.webp",
  "img/external/snowman-fallen.png": "img/web/snowman-fallen.a3514804e725.webp",
  "img/external/buildings/diary-lab.png": "img/web/diary-lab.f858c988a210.webp",
  "img/external/buildings/bookshop.png": "img/web/bookshop.d1aa56fa000e.webp",
  "player/seal-game.png": "img/web/seal-game.e47e428347fd.webp",
  "chat/georgia/avatar.png": "img/web/avatar.9f5b01e5beac.webp",
  "chat/georgia/georgie-bike.png": "img/web/georgie-bike.9f5b01e5beac.webp",
  "chat/mike/overworld-avatar.png": "img/web/overworld-avatar.a85e426feace.webp",
  "img/external/mike-aftermath.png": "img/web/mike-aftermath.bb28cb7e9478.webp",
  "chat/rei/overworld-avatar.png": "img/web/overworld-avatar.d5c4103d1343.webp",
  "chat/adam/avatar.png": "img/web/avatar.6d67dbbacf42.webp",
  "chat/tim/map-sprite.png": "img/web/map-sprite.ce443bf3798f.webp",
  "chat/niall/niall-sprite.png": "img/web/niall-sprite.21398072c37b.webp",
  "chat/siblings/girls-sprite.png": "img/web/girls-sprite.d75c09020b66.webp",
  "chat/bochra/map-sprite.png": "img/web/map-sprite.08c6c026197d.webp",
  "chat/katie/map-sprite.png": "img/web/map-sprite.524014429428.webp",
  "img/internal/cinema-popcorn-redrawn.png": "img/web/cinema-popcorn-redrawn.eb470bb4fc71.webp",
  "img/internal/cinema-open-door.png": "img/web/cinema-open-door.dfed51ae6913.webp",
  "img/internal/garden.png": "img/web/garden.cdab0e7718ed.webp",
  "img/internal/garden-door.png": "img/web/garden-door.cf8a0e55e74b.webp",
  "img/internal/internal-music.png": "img/web/internal-music.07580744c558.webp",
  "img/internal/internal-gym.png": "img/web/internal-gym.ea75b31ce3f6.webp",
  "img/internal/gym-door-open.png": "img/web/gym-door-open.25929306b27f.webp",
  "img/internal/bookshop-internal.png": "img/web/bookshop-internal.93b31c1dd5a3.webp",
  "img/internal/bookshop-door-open.png": "img/web/bookshop-door-open.dc8f43895e79.webp",
  "img/internal/mansion.png": "img/web/mansion.44c89e738fcd.webp",
  "img/internal/diary-lab.png": "img/web/diary-lab.d0abc7dca25b.webp",
  "img/internal/diary-lab-doors-out.png": "img/web/diary-lab-doors-out.13e2bdc1314a.webp"
};
